services:
  backend:
    env_file:
      - .env
      - .env.dev
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
      target: builder
    working_dir: /app
    command: yarn workspace backend start:dev
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      KAFKA_BROKERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
      LIVEKIT_SERVER_URL: ${LIVEKIT_DOCKER_URL}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      MONGODB_URI: ${MONGODB_DOCKER_URI}
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules

  frontend:
    env_file:
      - .env
      - .env.dev
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
      target: builder
    working_dir: /app
    command: yarn workspace frontend dev
    environment:
      NEXT_PUBLIC_LIVEKIT_URL: ${NEXT_PUBLIC_LIVEKIT_URL}
      NEXT_PUBLIC_LIVEKIT_ROOM: ${NEXT_PUBLIC_LIVEKIT_ROOM}
      NODE_OPTIONS: ${NODE_OPTIONS}
    volumes:
      - .:/app
      - root-node-modules:/app/node_modules
      - frontend-next-cache:/app/apps/frontend/.next

volumes:
  root-node-modules:
  frontend-next-cache:
