services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    profiles: ["infra"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./infra/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/certs:/etc/nginx/certs:ro
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env
      - .env.production

  redis:
    image: redis:alpine
    container_name: BB_redis
    profiles: ["infra", "livekit"]
    command: redis-server --appendonly yes # Enable data persistence
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

  livekit-redis:
    image: redis:alpine
    container_name: BB_livekit_redis
    profiles: ["livekit"]
    command: redis-server --appendonly yes
    volumes:
      - redis-livekit-data:/data
    ports:
      - "6380:6380"
      - "6379:6379" 
    restart: unless-stopped
    networks:
      - livekit-network

  livekit:
    image: livekit/livekit-server:latest
    container_name: BB_livekit
    profiles: ["livekit"]
    command:
      - --node-ip=83.166.251.174
      - --config
      - /etc/livekit.yaml
    volumes:
      - ./infra/livekit/livekit.yaml:/etc/livekit.yaml:ro
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "8000-8010:8000-8010/udp"
    depends_on:
      - livekit-redis
    restart: unless-stopped
    networks:
      - livekit-network
      - app-network

  egress:
    image: livekit/egress:latest
    container_name: BB_egress
    profiles: ["livekit"]
    environment:
      EGRESS_CONFIG_FILE: /etc/egress.yaml
    volumes:
      - ./infra/livekit/egress.yaml:/etc/egress.yaml
      - ./infra/livekit/recordings:/recordings
    cap_add:
      - SYS_ADMIN
    depends_on:
      - livekit
    restart: unless-stopped
    networks:
      - livekit-network
    env_file:
      - .env
      - .env.production

  broker:
    image: apache/kafka:latest
    container_name: BB_broker
    hostname: broker
    profiles: ["infra"]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    container_name: BB_postgres
    profiles: ["infra"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB} # on a first run, it will create a database with this name
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - app-network

  mlin:
    profiles: ["ml"]
    build:
      context: ./services/ml/MLin
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_GROUP_ID: ${MLIN_KAFKA_GROUP_ID}
      KAFKA_TOPICS: ${MLIN_KAFKA_TOPICS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - broker
      - redis
    restart: unless-stopped
    networks:
      - app-network

  mlout:
    profiles: ["ml"]
    build:
      context: ./services/ml/MLout
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_GROUP_ID: ${MLOUT_KAFKA_GROUP_ID}
      KAFKA_TOPICS: ${MLOUT_KAFKA_TOPICS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - broker
      - redis
    restart: unless-stopped
    networks:
      - app-network

  backend:
    profiles: ["web"]
    container_name: BB_backend
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      broker:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
      - .env.production
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${BACKEND_DATABASE_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

  frontend:
    profiles: ["web"]
    container_name: BB_frontend
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
      args:
        NEXT_PUBLIC_LIVEKIT_URL: ${NEXT_PUBLIC_LIVEKIT_URL}
        NEXT_PUBLIC_LIVEKIT_ROOM: ${NEXT_PUBLIC_LIVEKIT_ROOM}
    environment:
      NEXT_PUBLIC_LIVEKIT_URL: ${NEXT_PUBLIC_LIVEKIT_URL}
      NEXT_PUBLIC_LIVEKIT_ROOM: ${NEXT_PUBLIC_LIVEKIT_ROOM}
      NODE_OPTIONS: ${NODE_OPTIONS}
      PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
      - .env.production

networks:
  app-network:
    driver: bridge
  livekit-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  redis-livekit-data:
