version: "3.8"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - ml-net

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-livekit-data:/data
    ports:
      - "6380:6380"
    restart: unless-stopped
    networks:
      - livekit-network

  livekit:
    image: livekit/livekit-server:latest
    command:
      - --node-ip=83.166.251.174
      - --config
      - /etc/livekit.yaml
    container_name: livekit_server
    env_file:
      - .env
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "8000-8010:8000-8010/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - livekit-network

  egress:
    image: livekit/egress:latest
    environment:
      EGRESS_CONFIG_FILE: /etc/egress.yaml
    volumes:
      - ./egress.yaml:/etc/egress.yaml
      - ./recordings:/recordings
    cap_add:
      - SYS_ADMIN
    depends_on:
      - redis
      - livekit
    restart: unless-stopped
    networks:
      - livekit-network

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - ml-net

  context-storage:
    image: redis:7-alpine
    container_name: redis-context-storage
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ml-net
    command: redis-server --appendonly yes
  mlin:
    build:
      context: ./ml/MLin
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
      KAFKA_GROUP_ID: mlin_group
      KAFKA_TOPICS: speechEvent,boardEvent
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - broker
      - context-storage
    networks:
      - ml-net
    restart: unless-stopped

  mlout:
    build:
      context: ./ml/MLout
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
      KAFKA_GROUP_ID: mlout_group
      KAFKA_TOPICS: chatEvent,summaryEvent
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - broker
      - context-storage
    networks:
      - ml-net
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret_hehe_boy_a3f8c1e9b2d4f6a0c5e7b9d1f3a5c8e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4
      - LIVEKIT_URL=ws://livekit_server:7880
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - REDIS_HOST=context-storage
      - REDIS_PORT=6379 
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - broker
      - context-storage
    networks:
      - ml-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000
    shm_size: 2gb
    environment:
      - NEXT_PUBLIC_LIVEKIT_URL=ws://83.166.251.174:7880
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3080
      - NODE_OPTIONS=--max_old_space_size=4096
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - ml-net
    restart: unless-stopped

networks:
  ml-net:
    driver: bridge
  livekit-network:
    driver: bridge

volumes:
  redis-data:
  redis-livekit-data:
