# # Required fields
# api_key: livekit server api key. LIVEKIT_API_KEY env can be used instead
# api_secret: livekit server api secret. LIVEKIT_API_SECRET env can be used instead
# ws_url: livekit server websocket url. LIVEKIT_WS_URL can be used instead
# redis:
#   address: livekit-redis:6379
#   username: default
#   password: redis password
#   db: redis db

# # Optional fields
# health_port: if used, will open an http port for health checks
# template_port: port used to host default templates (default 7980)
# prometheus_port: port used to collect prometheus metrics. Used for autoscaling
# log_level: debug, info, warn, or error (default info)
# template_base: can be used to host custom templates (default http://localhost:<template_port>/)
# enable_chrome_sandbox: if true, egress will run Chrome with sandboxing enabled. This requires a specific Docker setup, see below.
# insecure: can be used to connect to an insecure websocket (default false)

# # File upload config - only one of the following. Can be overridden per-request
# s3:
#   access_key: AWS_ACCESS_KEY_ID env can be used instead
#   secret: AWS_SECRET_ACCESS_KEY env can be used instead
#   region: AWS_DEFAULT_REGION env can be used instead
#   endpoint: optional custom endpoint
#   bucket: bucket to upload files to
# azure:
#   account_name: AZURE_STORAGE_ACCOUNT env can be used instead
#   account_key: AZURE_STORAGE_KEY env can be used instead
#   container_name: container to upload files to
# gcp:
#   credentials_json: GOOGLE_APPLICATION_CREDENTIALS env can be used instead
#   bucket: bucket to upload files to

log_level: debug
# api_key: your-api-key LIVEKIT_API_KEY env can be used instead
# api_secret: your-api-secret LIVEKIT_API_SECRET env can be used instead
ws_url: ws://172.17.0.1:7880
insecure: true
redis:
  address: 172.17.0.1:6379